<?php 

$student_inventory = [
	'INSERT INTO inventory VALUES(
"AA01-005",
"Lord of the flies",
"British schoolboys are stranded on a tropical island.",
"William Golding",
"aa01-005.jpg",
1001,
6.38,
"Colchester",
15,
6 );',
	'INSERT INTO inventory VALUES(
"AA01-006",
"Nineteen Eighty-Four",
"Story of a man named Winston in a dystopian future",
"George Orwell",
"aa01-006.jpg",
1001,
5.99,
"Colchester",
12,
6);','INSERT INTO inventory VALUES (
"AA01-011",
"The Incredible True Story",
"The second studio album by American rapper Logic",
"Logic",
"aa01-011.jpg",
1002,
8.38,
"Colchester",
3,
1 );','INSERT INTO inventory VALUES (
"AA01-012",
"Oxygene Trilogy",
"The nineteenth studio album by the French electronic musician and composer Jean-Michel Jarre",
"Jean-Michel Jarre",
"aa01-012.jpg",
1002,
9.99,
"Colchester",
4,
3 );','INSERT INTO inventory VALUES(
"AA01-017",
"Halo Reach",
"Step into the boots of \'Noble 6\', The newly assigned Noble team Spartan, tasked to defend the dying planet of Reach ",
"Bungie",
"aa01-017.jpg",
1003,
28.99,
"Colchester",
300,
18);','INSERT INTO inventory VALUES(
"AA01-018",
"Halo 3",
"Finish the fight along with the Arbiter and the Master Chief",
"Bungie",
"aa01-018.jpg",
1003,
15.54,
"Colchester",
117,
12 );','INSERT INTO inventory VALUES(
"AA01-023",
"Tron",
"Jeff Bridges plays a computer programmer transported inside of a computer",
"Walt Disney Productions",
"aa01-023.jpg",
1004,
3.99,
"Colchester",
2,
6);','INSERT INTO inventory VALUES(
"AA01-024",
"Batman v Superman: Dawn of Justice",
"Batman faces Superman in the ultimate battle of heroes",
"DC Entertainment",
"aa01-024.jpg",
1004,
7.99,
"colchester",
6,
9);'
];

?>
